### ISSUE TITLE
mulle tundub, et selle võib lahti võtta ja viia sarnasele kujule kui ROS1 puhul.

### ISSUE THREAD

**Issue by kruusamae** [ut-ims-robotics-sandbox/Kristo_p_sandbox#2]
https://github.com/ut-ims-robotics-sandbox/Kristo_p_sandbox/blob/8872b3184df5ffe7241a2b5dd0e0b1a001fe8ddc/movegroup_interface_examples/src/joint_space_goal.cpp#L35-L39

**Comment by Kristo-P** [comment]
Nõustun, tegin nii.
